In [1]:
import numpy as np

In [18]:
a = np.array([1, 2, 3])
print(f"array a:\n {a}")

array a:
 [1 2 3]


In [19]:

b = np.arange(0,10,2)
print(f"array b:\n {b}")


array b:
 [0 2 4 6 8]


In [20]:
c = np.linspace(0,1,10).round(1)
print(f"array c:\n {c}")

array c:
 [0.  0.1 0.2 0.3 0.4 0.6 0.7 0.8 0.9 1. ]


In [21]:
c = np.linspace(1,10,100).round(1)
print(f"array c:\n {c}")

array c:
 [ 1.   1.1  1.2  1.3  1.4  1.5  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2
  2.3  2.4  2.5  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5
  3.5  3.6  3.7  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.5  4.6  4.7
  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5  5.5  5.6  5.7  5.8  5.9  6.
  6.1  6.2  6.3  6.4  6.5  6.5  6.6  6.7  6.8  6.9  7.   7.1  7.2  7.3
  7.4  7.5  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3  8.4  8.5  8.5
  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.5  9.6  9.7  9.8
  9.9 10. ]


In [22]:
d = np.zeros((2,3), dtype = "int")
print(f"array d:\n {d}")

array d:
 [[0 0 0]
 [0 0 0]]


In [23]:
e = np.ones((2,3), dtype = "int")
print(f"array e:\n {e}")

array e:
 [[1 1 1]
 [1 1 1]]


In [25]:
f = np.eye(4, dtype = "int")
print(f"array f:\n {f}")

array f:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


ARRAY MANIPULATION

In [32]:
a1 =np.array([1,2,3])
reshaped  = np.reshape(a1,(1,3))
print(f"reshaped array:\n {reshaped}")
a1

reshaped array:
 [[1 2 3]]


array([1, 2, 3])

In [33]:
reshaped

array([[1, 2, 3]])

In [35]:
f1 = np.array([[1,2,3],[4,5,6]])
flattened  = np.ravel(f1)
print(f"flattened array:\n {flattened}")
f1

flattened array:
 [1 2 3 4 5 6]


array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
x = np.arange(0,20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
x = np.reshape(x,(10,2))
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [41]:
x = np.ravel(x)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
t1 = np.arange(0,20).reshape(5,4)
transposed = np.transpose(t1)
print(f"transposed array:\n {transposed}")
t1

transposed array:
 [[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [44]:
s1 = np.array([1,2,3])
s2 = np.array([4,5,6])
stacked = np.stack((s1,s2))
print(f"stacked array:\n {stacked}")

stacked array:
 [[1 2 3]
 [4 5 6]]


MATHEMATICAL FUNCTIONS

In [49]:
math = np.array([1,2,3,4,5,6])
added = np.add(math, 2)
print(f"added array:\n {added}")

added array:
 [3 4 5 6 7 8]


In [50]:
subtracted = np.subtract(math, 2)
print(f"subtracted array:\n {subtracted}")

subtracted array:
 [-1  0  1  2  3  4]


In [51]:
powered  = np.power(math, 2)
print(f"powered array:\n {powered}")

powered array:
 [ 1  4  9 16 25 36]


In [52]:
squareroot  = np.sqrt(math)
print(f"squareroot array:\n {squareroot}")

squareroot array:
 [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [53]:
cuberoot  = np.cbrt(math)
print(f"cuberoot array:\n {cuberoot}")

cuberoot array:
 [1.         1.25992105 1.44224957 1.58740105 1.70997595 1.81712059]


In [54]:
a1

array([1, 2, 3])

In [57]:
a2  = np.array([2,3,4])
mul = np.dot(a1,a2)
print(f"dot product:\n {mul}")

dot product:
 20


In [58]:
div = np.divide(a1,a2)
print(f"divided array:\n {div}")

divided array:
 [0.5        0.66666667 0.75      ]


STATS   

In [59]:
s = np.array([0,1,2,3,4,5,6,7,8,9])
mean = np.mean(s)
print(f"mean of array:\n {mean}")

mean of array:
 4.5


In [60]:
standard_deviation = np.std(s)
print(f"standard deviation of array:\n {standard_deviation}")

standard deviation of array:
 2.8722813232690143


In [62]:
m = np.min(s)
print(f"minimum of array:\n {m}")

minimum of array:
 0


In [63]:
max = np.max(s)
print(f"maximum of array:\n {max}") 

maximum of array:
 9


LINEAR ALGEBRA  

In [66]:
ALG = np.arange(0,25).reshape(5,5)
print(f"array ALG:\n {ALG}")

array ALG:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [67]:
det = np.linalg.det(ALG)
print(f"determinant of ALG:\n {det}")

determinant of ALG:
 0.0


In [ ]:
alg = np.random.randint(0,10000000, size=(5,5))
print(f"array alg:\n {alg}")
inverse = np.linalg.inv(alg)
print(f"inverse of ALG:\n {inverse}")

array alg:
 [[8842230 8260920 7560050 1831367 6464809]
 [5850476  596709 2486234 6780389 2794973]
 [2718948 2218107 5683737 4217375 1555510]
 [4673638 3965732 5089321 5962546 2637122]
 [3732343 3297318 8864720 8658473 4054964]]
inverse of ALG:
 [[ 3.82811009e-08  1.85043781e-07  3.77197277e-07 -9.02709288e-08
  -2.74564968e-07]
 [-2.15072438e-08 -2.28352999e-07 -2.71497467e-07  5.16476897e-07
  -4.00533457e-08]
 [ 2.37855431e-08 -5.14926935e-09  4.20182774e-07 -2.63880095e-07
  -2.39438446e-08]
 [-9.27309594e-08 -9.77440252e-09 -2.07691440e-07  2.52650320e-07
   6.99398379e-08]
 [ 1.28261151e-07  4.74933500e-08 -6.01516574e-07 -2.99487079e-07
   4.34904609e-07]]


In [94]:
rand1 = np.random.rand(3)
print(f"random array:\n {rand1}")

random array:
 [0.53641604 0.77809443 0.8308828 ]


In [108]:
np.random.seed(0)
random_vals = np.random.rand(3)  #
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [ ]:
np.random.seed(0)
rando_int = np.random.randint(0,10, size = 5)
print(f"random integer array:\n {rando_int}")

random integer array:
 [5 0 3 3 7]


LOGIC TEST ALL, ANY

In [119]:
LOGIC = np.array([True, False, True, False])
print(f"array LOGIC:\n {LOGIC}")

array LOGIC:
 [ True False  True False]


In [120]:
all = np.all(LOGIC)
print(f"all elements are True:\n {all}")

all elements are True:
 False


In [121]:
any = np.any(LOGIC)
print(f"any element is True:\n {any}")

any element is True:
 True
