In [2]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

In [6]:
l = [0,1,2,3,4]
l1 = [5,6,7,8,9]
print(f"The elements in list 1 are {l} and the elements in list 2 are {l1}")

The elements in list 1 are [0, 1, 2, 3, 4] and the elements in list 2 are [5, 6, 7, 8, 9]


In [8]:

user_input = input("Enter 5 numbers separated by spaces: ")

user_list = list(map(int, user_input.split()))

Enter 5 numbers separated by spaces:  1 2 3 4 5


In [10]:
user_list

[1, 2, 3, 4, 5]

In [12]:
u1 = input("Enter the values u want to add in the list seperated by a space : ")

Enter the values u want to add in the list seperated by a space :  33 44 55 66 77 88 99 


In [16]:
ul1 = list(map(int, u1.split()))

In [18]:
print(f"the list given is {ul1}")

the list given is [33, 44, 55, 66, 77, 88, 99]


In [20]:
u2 = input("Enter the elements u want to add in the list seperated by a space: ")

Enter the elements u want to add in the list seperated by a space:  1 2 3 4 5


In [24]:
ul2 = list(map(int, u2.split()))
print(f"The elements after adding into the list are{ul2}")

The elements after adding into the list are[1, 2, 3, 4, 5]


In [30]:
new_list = list(map(int, input("enter 5 elements which u wan to add int the list seperated by a space  : ").split()))

enter 5 elements which u wan to add int the list seperated by a space  :  1 2 3 4 5


In [32]:
print(f"the list created contains the elements{new_list}")

the list created contains the elements[1, 2, 3, 4, 5]


In [38]:
new2 = list(map(int, input("enter 5 elements seperated by space :").split()))
new2

enter 5 elements seperated by space : 33 44 7 63 81


[33, 44, 7, 63, 81]

In [40]:
arr1 = np.array(new_list)
arr2 = np.array(new2)
print(arr1,arr2)

[1 2 3 4 5] [33 44  7 63 81]


In [42]:
arr3 = arr1 + arr2
arr3

array([34, 46, 10, 67, 86])

In [46]:
arr4 = np.array([arr1,arr2])
print(arr4)

[[ 1  2  3  4  5]
 [33 44  7 63 81]]


In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [62]:
arr5 = np.array([np.arange(10),np.arange(10)])

In [58]:
arr5

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [66]:
arr6 = np.column_stack([arr1,arr2])

In [68]:
arr6

array([[ 1, 33],
       [ 2, 44],
       [ 3,  7],
       [ 4, 63],
       [ 5, 81]])

In [76]:
neww = list(map(int,input("Enter the elements with which u want to create a list: ").split()))
neww

Enter the elements with which u want to create a list:  99 88 77 66


[99, 88, 77, 66]

In [78]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
np.zeros((10,5),dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [86]:
neww1 = np.array([np.zeros(10,dtype = int),np.ones(10,dtype = int)])

In [88]:
neww1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [94]:
np.random.rand(1,3)

array([[0.59257534, 0.35011439, 0.58805578]])

In [96]:
np.random.randint(10,20)

10

In [104]:
np.random.randint(0,9,4)

array([2, 4, 6, 1])

In [116]:
neww3 = np.array([np.random.randint(0,1000,5),np.random.randint(0,1000,5)])

In [118]:
neww3

array([[549, 980, 669, 436, 289],
       [ 34, 580, 152,  73, 634]])

In [122]:
np.array(np.random.randint(10,100,10))

array([71, 68, 98, 75, 68, 88, 70, 20, 50, 52])

In [132]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [136]:
np.zeros(12,dtype = int).reshape(4,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])