In [308]:
import numpy as np

In [310]:
np.__version__

'1.26.4'

In [312]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# CREATING LIST

In [315]:
mylist1 =  [6,7,8,9,10]

In [317]:
my_list = [1,2,3,4,5]
my_list


[1, 2, 3, 4, 5]

# WE ARE CONVERTING LIST TO ARRAY

In [320]:
arr = np.array([my_list,mylist1])
type(arr)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [322]:
type(my_list)

list

In [324]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [326]:
np.arange(3.0)

array([0., 1., 2.])

In [328]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [330]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [331]:
np.arange(0 , 5)

array([0, 1, 2, 3, 4])

In [332]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [333]:
 np.arange(20,10)

array([], dtype=int32)

In [334]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [335]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [336]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [337]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [338]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [339]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [ ]:
np.zeros(10) # parameter tunning

In [ ]:
np.zeros(10,dtype = int) # hyper parameter tunning

In [340]:
np.zeros((2,2), dtype = int)

array([[0, 0],
       [0, 0]])

In [341]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [342]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [343]:
np.zeros((10,20),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [344]:
np.ones(3)

array([1., 1., 1.])

In [345]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [346]:
np.ones((3,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [347]:
rand(3,2)

NameError: name 'rand' is not defined

In [348]:
random.random(3,2)

NameError: name 'random' is not defined

In [ ]:
np.random.rand(3,2)

In [349]:
np.random.rand(5)

array([0.46649418, 0.65549556, 0.70750946, 0.3024495 , 0.67032057])

In [350]:
np.random.rand((3,2),dtype=int)

TypeError: rand() got an unexpected keyword argument 'dtype'

In [351]:
np.random.randint(4,6)

4

In [352]:
np.random.randint(3,30)

17

In [353]:
np.random.randint(0,10,4)

array([4, 8, 1, 9])

In [354]:
np.random.randint(10,20,5)

array([16, 19, 10, 19, 10])

In [355]:
np.random.randint(10,40,(10,5))

array([[27, 28, 17, 27, 11],
       [12, 23, 34, 34, 13],
       [25, 23, 35, 15, 22],
       [11, 13, 13, 36, 31],
       [14, 25, 11, 24, 25],
       [14, 28, 23, 29, 25],
       [10, 18, 30, 15, 36],
       [38, 25, 22, 19, 18],
       [39, 33, 20, 26, 29],
       [32, 14, 22, 28, 30]])

In [356]:
np.arange(1,13)



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [357]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [358]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [359]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [360]:
b = np.random.randint(10,20,(5,4))
b

array([[17, 12, 13, 18],
       [14, 11, 11, 19],
       [14, 18, 18, 12],
       [18, 17, 17, 10],
       [14, 10, 16, 13]])

In [361]:
b[:]

array([[17, 12, 13, 18],
       [14, 11, 11, 19],
       [14, 18, 18, 12],
       [18, 17, 17, 10],
       [14, 10, 16, 13]])

In [362]:
b[1:3]

array([[14, 11, 11, 19],
       [14, 18, 18, 12]])

In [363]:
b[1,2]

11

In [364]:
b


array([[17, 12, 13, 18],
       [14, 11, 11, 19],
       [14, 18, 18, 12],
       [18, 17, 17, 10],
       [14, 10, 16, 13]])

In [365]:
b[1,3]

19

In [366]:
b[1,-1]

19

In [367]:
b[2:3]

array([[14, 18, 18, 12]])

In [368]:
b[0:-2]

array([[17, 12, 13, 18],
       [14, 11, 11, 19],
       [14, 18, 18, 12]])

In [369]:
__name__

'__main__'

In [370]:
a = np.random.randint(10,20,10)

In [371]:
a

array([18, 10, 12, 19, 12, 10, 18, 13, 11, 10])

In [372]:
arr2

array([[60, 77,  6, 53, 36, 25,  6, 48, 80, 44],
       [75, 20, 77, 88, 74, 76,  6, 89, 98, 39],
       [18, 62, 77, 20, 78, 54, 57, 43, 71, 11],
       [15, 24, 23, 53, 44, 29, 43, 12, 52, 12],
       [87, 77, 68, 82, 89, 75, 15, 20,  1, 46],
       [72, 38, 16, 80, 40, 41, 64, 24, 56, 24],
       [66, 75, 22, 10, 88, 20, 20, 11, 84, 62],
       [80, 25, 22, 69, 54, 23, 64, 28, 23, 34],
       [36, 40, 90, 23, 49, 12,  4, 31, 56, 44],
       [39, 45, 24, 13, 26, 75, 55, 71, 46, 38]])

In [373]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [374]:
arr2 = np.random.randint(0,100,(10,10))

In [375]:
arr2

array([[72, 43, 96, 80,  8, 62,  2, 11, 47, 51],
       [89,  3, 14, 18, 57,  4,  7, 47, 31, 92],
       [85, 36, 41, 29, 62, 18, 85, 95, 45, 19],
       [ 6, 89, 71, 94, 69, 58, 34, 78,  7, 47],
       [81, 47, 83, 16, 18, 90, 75, 67, 72, 59],
       [10, 35, 12, 52, 13, 78,  5, 58, 20,  9],
       [25, 51, 72, 16, 12, 54,  3, 18, 37, 26],
       [25, 52, 30, 27, 25,  6, 42, 57, 36, 45],
       [43, 99, 61, 31, 47, 56, 56, 21, 46, 59],
       [83, 25, 78, 23, 62, 29, 66, 15, 31, 42]])

In [376]:
 arr2[3,4]

69

In [377]:
arr2 [2:3,3:5]

array([[29, 62]])

In [378]:
arr2[:,5:]

array([[62,  2, 11, 47, 51],
       [ 4,  7, 47, 31, 92],
       [18, 85, 95, 45, 19],
       [58, 34, 78,  7, 47],
       [90, 75, 67, 72, 59],
       [78,  5, 58, 20,  9],
       [54,  3, 18, 37, 26],
       [ 6, 42, 57, 36, 45],
       [56, 56, 21, 46, 59],
       [29, 66, 15, 31, 42]])

In [457]:
h =  np.random.randint(0,65,(8,8))

In [500]:
h = np.sort(h) 

In [502]:
h

array([[ 6, 13, 29, 40, 44, 49, 50, 50],
       [ 4, 24, 24, 34, 55, 56, 59, 63],
       [ 1, 10, 13, 15, 45, 51, 60, 62],
       [13, 23, 34, 39, 45, 49, 56, 60],
       [ 3, 16, 21, 36, 41, 46, 46, 59],
       [ 4, 10, 21, 34, 36, 39, 45, 50],
       [ 3,  7, 14, 28, 35, 37, 54, 57],
       [ 7, 17, 21, 30, 36, 37, 40, 60]])

In [498]:
h[h<=15]

array([13,  6,  4, 15, 13,  1, 10, 13,  3,  4, 10,  7,  3, 14,  7])

In [488]:
h1 = h[h>=40]
h1

array([44, 49, 50, 50, 40, 56, 55, 63, 59, 60, 51, 62, 45, 56, 60, 49, 45,
       59, 46, 46, 41, 45, 50, 57, 54, 60, 40])

In [494]:
h1 = np.sort(h1)[::-1]

In [496]:
h1

array([63, 62, 60, 60, 60, 59, 59, 57, 56, 56, 55, 54, 51, 50, 50, 50, 49,
       49, 46, 46, 45, 45, 45, 44, 41, 40, 40])

In [508]:
mat = np.arange(0,100).reshape(10,10,order = "F")

In [510]:
mat

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [512]:
mat[2:5,4:7]

array([[42, 52, 62],
       [43, 53, 63],
       [44, 54, 64]])